export const contentList: string[] = [
    "Living things",
    "Animal kingdom",
    "Animals",
    "Mammal",
    "Bird",
    "Reptiles and amphibians",
    "Arthropods",
    "Aquatic animals",
    "Worms and snails",
    "Body parts of animals",
    "Animal sounds",
    "Excreta of animals",
    "Animal homes",
    "Animal brood",
    "Other words related to animals",
    "Adjective related to animals",
    "Human beings",
    "Parts of human body",
    "Secretions and excretions",
    "Disease, illness, malady",
    "Symptoms and other disorders",
    "Words related to hair",
    "Words related to skin",
    "Words describing features of body",
    "Other words related to human body",
    "Plant kingdom",
    "Plant life",
    "Plants variety",
    "Flowering plants",
    "Flowers from trees",
    "Flowers from shrubs and herbs",
    "Flowers from creepers, bushes",
    "Flowers from aquatic plants",
    "Fruit plants",
    "Fruits and nuts from trees",
    "Fruits from creepers and vines",
    "Grain and pulses",
    "Medicinal plants",
    "Medicinal trees",
    "Medicinal shrubs, small trees",
    "Medicinal herbs",
    "Medicinal creepers and vines",
    "Millets",
    "Oilseeds",
    "Spices",
    "Timber trees",
    "Vegetables",
    "Leafy vegetables",
    "Vegetables on shrubs",
    "Vegetables from trees",
    "Vegetables from creepers, climbers",
    "Tubers, corms and bulbs used as vegetables",
    "Other useful trees, shrubs",
    "Plant Parts",
    "Parts of plants",
    "Parts of jackfruit tree",
    "Parts of plantain tree",
    "Parts of betel palm",
    "Parts of a coconut palm",
    "Parts of a mango tree",
    "Parts of paddy",
    "Other words related to plants",
    "Non-living things",
    "Clothing and jewellery",
    "Apparel and foot wear",
    "Types of sarees",
    "Other words related to apparel",
    "Fabric or cloth",
    "Jewellery",
    "Gems",
    "Buildings",
    "Parts of a house or building",
    "Rooms of a house",
    "Prayer room",
    "Inside house",
    "Furniture",
    "Other items inside house",
    "Sleeping paraphernalia in bedroom",
    "Kitchen",
    "Items in Kitchen",
    "Cooking oils",
    "Grocery etc.",
    "Other items in kitchen",
    "Residue, remnants",
    "Utensils and accessories",
    "Bath room",
    "Tools, instruments, weapons",
    "Outside house",
    "Language, food and culture",
    "Language",
    "Baby language",
    "Baby language nouns",
    "Baby language verbs",
    "Affectionate words for baby's body parts",
    "Words of address",
    "Compound words",
    "Compound adjectives",
    "Compound adverbs",
    "Compound nouns",
    "Echo words",
    "Languages",
    "Lexical doublets",
    "Lexical doublet adjectives",
    "Lexical doublet adverbs",
    "Lexical doublet nouns",
    "Proverbs",
    "Riddles",
    "Reduplicative words",
    "Adjective-adjective Reduplication 1",
    "Adjective-adjective Reduplication 2",
    "Adverb-adverb Reduplication",
    "Function Reduplication",
    "Noun-noun Reduplication: quantitative 1",
    "Noun-noun Reduplication: quantitative 2",
    "Noun-noun Reduplication: quantitative 3",
    "Numeral numeral Reduplication",
    "Possessive Reduplication",
    "Verb-verb Reduplication",
    "Simile",
    "Case form",
    "Idioms",
    "Imperatives",
    "Imperative verbs",
    "Negative imperatives",
    "Requesting imperatives",
    "Interrogatives",
    "Interrogative phrases",
    "Interrogative words",
    "Opposites, antonyms",
    "Onomatopoeic words",
    "Onomatopoeic adjectives",
    "Onomatopoeic adverbs",
    "Onomatopoeic nouns",
    "Onomatopoeic verbs",
    "Onomatopoeic verbs starting with letter क",
    "Onomatopoeic verbs starting with letter ख",
    "Onomatopoeic verbs starting with letter ग",
    "Onomatopoeic verbs starting with letter घ",
    "Onomatopoeic verbs starting with letter च",
    "Onomatopoeic verbs starting with letters छ, ज and झ",
    "Onomatopoeic verbs starting with letters ट, ठ and ड",
    "Onomatopoeic verbs starting with letters त, थ, द, ध and न",
    "Onomatopoeic verbs starting with letter प",
    "Onomatopoeic verbs starting with letter फ",
    "Onomatopoeic verbs starting with letters ब and भ",
    "Onomatopoeic verbs starting with letter म",
    "Onomatopoeic verbs starting with letters य, र and ल",
    "Onomatopoeic verbs starting with letter व",
    "Onomatopoeic verbs starting with letters श, स and ष",
    "Onomatopoeic verbs starting with letter ह",
    "Parts of Speech",
    "Adjectives",
    "Adjectives for action",
    "Adjectives for age",
    "Adjectives for appearance",
    "Adjectives for circumstances",
    "Adjectives for colour",
    "Adjectives for condition of food",
    "Adjectives for condition of nature",
    "Adjectives for condition of objects",
    "Adjectives for condition of person",
    "Adjectives for condition of place",
    "Adjectives for direction",
    "Adjectives for domicile",
    "Adjectives for emotion or feeling",
    "Adjectives for features for nature",
    "Adjectives for features of food",
    "Adjectives for features of objects",
    "Adjectives for general location",
    "Adjectives for location on body",
    "Adjectives for material",
    "Adjectives for opinion, perception, impression",
    "Adjectives for personality",
    "Adjectives for position",
    "Adjectives for purpose",
    "Adjectives for quantity",
    "Adjectives for relation",
    "Adjectives for shapes and patterns",
    "Adjectives for situations",
    "Adjectives for size",
    "Adjectives for smell",
    "Adjectives for sound",
    "Adjectives for speed",
    "Adjectives for taste",
    "Adjectives for temperature",
    "Adjectives for time period",
    "Adjectives for topography",
    "Adjectives for touch",
    "Adjectives for traits",
    "Adjectives for type",
    "Adjectives for weight",
    "Complimentary adjectives",
    "Definite numeral adjectives",
    "Demonstrative adjectives",
    "Indefinite numeral adjectives",
    "Other miscellaneous adjectives",
    "Other miscellaneous adjectives shared with other indian languages",
    "Adverbs",
    "Adverbs of Degree or Quantity",
    "Adverbs of Minimal",
    "Adverbs of Category",
    "Adverbs of Excess",
    "Adverbs of Comparison",
    "Adverbs of Adequate",
    "Adverbs of Manner",
    "Adverbs of Method",
    "Adverbs of Indecisiveness",
    "Adverbs of Decisiveness",
    "Adverbs of Purpose",
    "Adverbs of Negation",
    "Adverbs of Concept",
    "Adverbs of Description",
    "Adverbs of Affirmation",
    "Adverbs of Place",
    "Adverbs of Direction",
    "Adverbs of Position",
    "Adverbs of Time",
    "Adverbs of Time Point",
    "Adverbs of Frequency",
    "Adverbs of Duration",
    "Misc Adverbs",
    "Conjunction",
    "Nouns",
    "Abstract nouns",
    "Collective noun",
    "Common nouns",
    "Community nouns",
    "Countable nouns",
    "Countable nouns for aperture",
    "Mass nouns or uncountable nouns",
    "Nouns based on form",
    "Nouns denoting portion, share etc.",
    "Nouns for punishment",
    "Nouns related to dimension and state",
    "Nouns shared with other indian languages with konkanised spellings",
    "Occupational nouns",
    "Root word",
    "Sensory nouns",
    "Sensory nouns related to sight or appearance",
    "Sensory nouns related to smell",
    "Sensory nouns related to sound",
    "Sensory nouns related to taste",
    "Sensory nouns related to touch",
    "Special trait nouns",
    "Trait noun",
    "Uncountable nouns",
    "Verbal noun",
    "Preposition or Postpositions",
    "Pronouns",
    "Personal Pronouns",
    "Subjective Pronouns",
    "Objective Pronouns",
    "Demonstrative Pronouns",
    "Indefinite Pronouns",
    "Compound Personal Pronoun",
    "Reflexive Pronouns 1",
    "Reflexive Pronouns 2",
    "Intensive Pronouns",
    "Oblique case",
    "Possessive Pronouns",
    "Possessive Pronouns (Absolute 1)",
    "Possessive Pronouns (Absolute 2)",
    "Possessive Pronouns (Adjective 1)",
    "Possessive Pronouns (Adjective 2)",
    "Instrumental case of Pronouns 1",
    "Instrumental case of Pronouns 2",
    "Dative case of Pronouns 1",
    "Dative case of Pronouns 2",
    "Ablative case of Pronouns",
    "Accusative case of Pronouns",
    "Locative case of Pronouns 1",
    "Locative case of Pronouns 2",
    "Declension of Demonstrative Pronouns",
    "Verb",
    "Verbs starting with letter अ",
    "Verbs starting with letter आ",
    "Verbs starting with letters इ,ई and उ",
    "Verbs starting with letter ऊ",
    "Verbs starting with letters ए, ऐ, ओ and औ",
    "Verbs starting with letter क",
    "Verbs starting with letter का",
    "Verbs starting with letters कि and की",
    "Verbs starting with letters कु and कू",
    "Verbs starting with letters के, को and कौ",
    "Verbs starting with letter ख",
    "Verbs starting with letter खा",
    "Verbs starting with letters खि and खी",
    "Verbs starting with letters खु, खू, खे,and खै",
    "Verbs starting with letters खो and खौ",
    "Verbs starting with letter ग",
    "Verbs starting with letter गा",
    "Verbs starting with letters गि, गी, गु and गू",
    "Verbs starting with letters गो and गौ",
    "Verbs starting with letter घ",
    "Verbs starting with letter घा",
    "Verbs starting with letter घु and घू",
    "Verbs starting with letters घे, घै, घो and घौ",
    "Verbs starting with letter च",
    "Verbs starting with letter चा",
    "Verbs starting with letters चि and ची",
    "Verbs starting with letters चु, चू,चे and चै",
    "Verbs starting with letters चो and चौ",
    "Verbs starting with letter छ",
    "Verbs starting with letter ज",
    "Verbs starting with letter जा",
    "Verbs starting with letters जि and जी",
    "Verbs starting with letters जु, जू, जे and जै",
    "Verbs starting with letters जो and जौ",
    "Verbs starting with letters झ and झा",
    "Verbs starting with letters झि, झी, झु, झू, झे, झै, झो and झौ",
    "Verbs starting with letter ट",
    "Verbs starting with letter ड",
    "Verbs starting with letter ढ",
    "Verbs starting with letter त",
    "Verbs starting with letter ता",
    "Verbs starting with letters ति, ती, तु and तू",
    "Verbs starting with letters तृ, ते, तै, तो and तौ",
    "Verbs starting with letter थ",
    "Verbs starting with letters द and दा",
    "Verbs starting with letters दि and दी",
    "Verbs starting with letters दु and दू",
    "Verbs starting with letters दे, दै, दो and दौ",
    "Verbs starting with letters ध and धा",
    "Verbs starting with letters धि,धी,धु and धू",
    "Verbs starting with letters धे, धै, धो and धौ",
    "Verbs starting with letters न and ना",
    "Verbs starting with letter नि",
    "Verbs starting with letter नी",
    "Verbs starting with letters नु, नू, ने, नै, नो and नौ",
    "Verbs starting with letter न्ह",
    "Verbs starting with letter प",
    "Verbs starting with letter पा",
    "Verbs starting with letter पि",
    "Verbs starting with letter पी",
    "Verbs starting with letter पु",
    "Verbs starting with letter पू",
    "Verbs starting with letters पे and पै",
    "Verbs starting with letters पो and पौ",
    "Verbs starting with letter प्र",
    "Verbs starting with letter फ",
    "Verbs starting with letter फा",
    "Verbs starting with letters फि, फी, फु and फू",
    "Verbs starting with letters फे, फै, फो and फौ",
    "Verbs starting with letter ब",
    "Verbs starting with letter बा",
    "Verbs starting with letters बि, बी, बु and बू",
    "Verbs starting with letters बे and बै",
    "Verbs starting with letters बो and बौ",
    "Verbs starting with letters भ and भा",
    "Verbs starting with letters भि and भी",
    "Verbs starting with letters भु and भू",
    "Verbs starting with letters भे, भै, भो and भौ",
    "Verbs starting with letter म",
    "Verbs starting with letter मा",
    "Verbs starting with letters मि and मी",
    "Verbs starting with letters मु and मू",
    "Verbs starting with letters मृ, मे and मै",
    "Verbs starting with letters मो, मौ and म्ह",
    "Verbs starting with letter य",
    "Verbs starting with letter र",
    "Verbs starting with letters रा",
    "Verbs starting with letters रि and री",
    "Verbs starting with letters रु, रू, रे, रै, रो and रौ",
    "Verbs starting with letter ल",
    "Verbs starting with letter ला",
    "Verbs starting with letters लि, ली, ले and लै ",
    "Verbs starting with letters लो, लौ and ल्ह",
    "Verbs starting with letter व",
    "Verbs starting with letter वा",
    "Verbs starting with letters वि and वी",
    "Verbs starting with letters वे and वै",
    "Verbs starting with letters वो and वौ",
    "Verbs starting with letter व्ह",
    "Verbs starting with letters श and शा",
    "Verbs starting with letters शि and शी",
    "Verbs starting with letters शु, शू, शे and शै",
    "Verbs starting with letters शो, शौ, श्र and श्व",
    "Verbs starting with letter स",
    "Verbs starting with letter सा",
    "Verbs starting with letters सि, सी, सु and सू",
    "Verbs starting with letters से, सै, सो and सौ",
    "Verbs starting with letters स्त, स्थ, स्फ and स्व",
    "Verbs starting with letter ह",
    "Verbs starting with letter हा",
    "Verbs starting with letters हि, ही, हु and हू",
    "Verbs starting with letters हे, है, हो and हौ",
    "Singular-plural",
    "Immediate Future",
    "Probable Future tense",
    "Transitional phrases",
    "Transitional words based on Time, Cronology, Sequence",
    "Transitional words based on Cause and Effect",
    "Food",
    "Cooked food",
    "Water and beverages",
    "Sweets",
    "Sweet food items",
    "Ball shaped sweet",
    "Sweet flat bread",
    "Jelly like sweet",
    "Soft flat sweet",
    "Soft rice sweet",
    "Semolina pudding",
    "Sweet batter covered ball",
    "Sweet flat dumpling",
    "Sweet mix",
    "Indian dessert",
    "Sweet pudding with jaggery or sugar",
    "Sweet fruit pudding",
    "Sweet pudding dessert",
    "Sweet pudding",
    "Sweet and savoury dishes",
    "Sweet dishes",
    "Sweet savoury dish of fruits",
    "Sweet fruit dish",
    "Thin sweet dish",
    "Sweet savoury dish with coconut",
    "Sweet savoury dry dish",
    "Deep fried food items",
    "Deep fried snacks",
    "Spicy deep fried fritter of chickpea batter",
    "Deep fried dry snacks",
    "Deep fried chips",
    "Deep fried finger chips",
    "Spicy deep fried fritter of rice flour",
    "Steamed cakes and pancakes",
    "Indian pancake",
    "Steamed cakes",
    "Moist snacks",
    "Variety of cooked rice",
    "Main dishes",
    "Spiced curry used to mix with rice",
    "Weak slightly sour dish with coconut",
    "Major dish",
    "Main curry with curd",
    "Main curry with coconut",
    "Main curry or dish",
    "Main curry or dish with a roasted and ground coconut masala",
    "Sub dishes",
    "Sub curry or dish",
    "Sub dish with coconut",
    "Sub dish with buttermilk",
    "Wet sub dish",
    "Side dish",
    "Coconut based stir fry",
    "Dry sub dish",
    "Salad or cold dish",
    "Cold dish",
    "Hot spicy pickle and stuff",
    "Hot spicy",
    "Fresh sour fruits seasoned",
    "Wet pickle",
    "Dry pickle",
    "Fresh pickle",
    "Squeezed pickle",
    "Pounded and crushed pickle",
    "Fresh pickle with fried vegetables",
    "Spicy hot curry",
    "Cured and dried",
    "Dried and fried items",
    "Dried and deep fried items",
    "Sun dried fritters",
    "Cured, dried and deep fried",
    "Crispy thin cracker dried and deep fried",
    "Culture",
    "Sixteen rites of passage",
    "Marriage",
    "Other words related to wedding",
    "Words related to pre wedding",
    "Customs related to wedding ceremony",
    "Post wedding customs",
    "Eight auspicious items",
    "Gifts given to the groom",
    "Upanayanam or sacred thread ceremony",
    "words related to upanayanam",
    "Verbs related to upanayanam",
    "Other minor rites",
    "Death ceremony",
    "Other rituals and poojas",
    "Rangoli at tulasi",
    "Decorative or sacred mark",
    "Festivals",
    "Festivals celebrated at home",
    "Festivals celebrated at temples",
    "Rituals and poojas related to Navaratri;",
    "Other celebrations",
    "Community festivals",
    "Special food items made at homes on festival days",
    "Verbs related to customs and rituals",
    "Lengthy periods of worship",
    "Temple",
    "Words related to temple",
    "Verbs related to temple",
    "Parts of a temple",
    "Items used in temple",
    "Nivedhyams in temple",
    "Annual temple festival",
    "Relation",
    "Gotras",
    "Relationship",
    "Other nouns for relation",
    "Time and space",
    "Astrology and astronomy",
    "Nine planets of astrology",
    "Nine planets of solar system",
    "Corresponding western zodiac for hindu astrological stars",
    "Other words related to astrology",
    "Days of a week",
    "Fortnight",
    "Bright lunar fortnight or period of waxing moon",
    "Dark lunar fortnight or period of waning moon",
    "Months",
    "Time and Period",
    "Seasons",
    "Time",
    "Time and Period",
    "Words related to time and day",
    "Numbers and measurements",
    "Numbers",
    "Cardinal numbers",
    "Ordinal numbers, Numerical adjectives",
    "Measurements",
    "Length measured using body parts",
    "Width measured using hand",
    "Weight of gold measured using objects",
    "Depth measured using body parts",
    "Measure of quantity",
    "Quantity measured using hands",
    "Measures of volume for grains or liquid",
    "Measures adapted from Malayalam for grains",
    "Other words related to measurements",
    "Other general vocabulary",
    "Agriculture",
    "Nouns relating to agriculture",
    "Verbs related to agriculture",
    "Capital and accounts",
    "Colours",
    "Main colours",
    "Other colours",
    "Directions",
    "Edges and points",
    "Fireworks, pyrotechnics",
    "Flower strings",
    "Habitat",
    "Kings and kingdoms",
    "Languages",
    "Medicine",
    "Minerals",
    "Musical instruments",
    "Nature",
    "Paths and lanes",
    "Vehicles and parts",
    "Words related to games",
    "Extra vocabulary",
  ];